feat: Criação de Roteiro de Entrevista
Lawd-UFS/backend-ps pull request #12
Opened 2024-12-08 16:44 UTC by alvarolspeixoto

# Criação de Roteiro de Entrevista

# Descrição
**Issue relacionada:**  
Closes #7 
Obs.: No modelo definido para a entrevista na issue, não estava presente o atributo da data em que a entrevista foi realizada, imaginei que seria necessário e adicionei (definido como `date` na model `Interview`).

# Alterações Realizadas

- [x] Adição de rota para criação de entrevistas
- [x] Adição de rota para criação de avaliadores (não é dessa issue, mas ainda não existia) 
- [x] Altera permissão de acesso do front ao back (cors)

# Testes Realizados

- [x] Teste 1: Criação de avaliador
- [x] Teste 2: Criação de entrevista

# Passos para Testar

1. Acessar a rota /api-docs
2. Experimentar as rotas POST /api/avaliadores e /api/entrevistas preenchendo os valores necessários
3. Observar retorno e validações

# Checklist

- [x] A implementação segue os critérios definidos.
- [x] Foram realizados testes locais (exceto a parte do cors).
- [x] A documentação foi atualizada (se aplicável).

2025-01-13 19:28 UTC, davibital requested changes
Tudo funcionando corretamente!

Porém é necessário também ter de fato o roteiro da entrevista, sem a resposta dos candidatos.

Esse roteiro servirá basicamente para possibilitar a consulta direta das perguntas da entrevista sem ser vinculada a um candidato ou avaliador específico.

Já que o roteiro ainda não está definido, deve ser utilizado um modelo de exemplo, inclusive a estrutura que você propôs está ótima!

`Obs.: Para o roteiro de perguntas e respostas que será "fixo", pode ser utilizado um arquivo *JSON* ou uma constante no código, além da alternativa de manter o registro de roteiro no banco de dados.`

2025-01-20 02:43 UTC, alvarolspeixoto commented
> Tudo funcionando corretamente!
> 
> Porém é necessário também ter de fato o roteiro da entrevista, sem a resposta dos candidatos.
> 
> Esse roteiro servirá basicamente para possibilitar a consulta direta das perguntas da entrevista sem ser vinculada a um candidato ou avaliador específico.
> 
> Já que o roteiro ainda não está definido, deve ser utilizado um modelo de exemplo, inclusive a estrutura que você propôs está ótima!
> 
> `Obs.: Para o roteiro de perguntas e respostas que será "fixo", pode ser utilizado um arquivo *JSON* ou uma constante no código, além da alternativa de manter o registro de roteiro no banco de dados.`

@davibital A ideia do roteiro é ter, basicamente, um conjunto de perguntas meio que "estático" só pro front poder consultar em alguma tela? antes mesmo desse roteiro ser usado na entrevista de algum candidato e ter associação com ele?

2025-01-20 14:16 UTC, davibital commented
> > Tudo funcionando corretamente!
> > Porém é necessário também ter de fato o roteiro da entrevista, sem a resposta dos candidatos.
> > Esse roteiro servirá basicamente para possibilitar a consulta direta das perguntas da entrevista sem ser vinculada a um candidato ou avaliador específico.
> > Já que o roteiro ainda não está definido, deve ser utilizado um modelo de exemplo, inclusive a estrutura que você propôs está ótima!
> > `Obs.: Para o roteiro de perguntas e respostas que será "fixo", pode ser utilizado um arquivo *JSON* ou uma constante no código, além da alternativa de manter o registro de roteiro no banco de dados.`
> 
> @davibital A ideia do roteiro é ter, basicamente, um conjunto de perguntas meio que "estático" só pro front poder consultar em alguma tela? antes mesmo desse roteiro ser usado na entrevista de algum candidato e ter associação com ele?

Exatamente, o conjuto de perguntas é fixo e estático por padrão, sem nenhuma informação de resposta para a pergunta ou outro tipo de classificação. E a cada entrevista com os candidatos, esse roteiro fixo terá respostas e classificações para as perguntas.

2025-01-23 16:38 UTC, davibital reviewed
@alvarolspeixoto Dessa forma o frontend iria obter esse roteiro estático para disponibilizar em tela, a entrevista ocorre e já ao final da entrevista, é feito o `POST` na rota de criação das entrevistas com as respostas para cada pergunta, correto?

2025-01-24 12:27 UTC, merged