Implementação da rota /api/horarios
Lawd-UFS/backend-ps pull request #3
Opened 2024-08-03 21:41 UTC by alvarolspeixoto

2024-08-06 14:54 UTC, davibital requested changes
Fora algumas pontuações, o endpoint foi bem implementado e seguiu um ótimo padrão de código!

2024-08-06 14:54 UTC, davibital commented on src/controllers/schedule-controller.ts
> +export const createSchedule = async (req: Request, res: Response) => {
É interessante que a requisição e a resposta sejam tipadas para todas as rotas da api, para maior consistência e também documentação da rota

2024-08-06 14:54 UTC, davibital commented on src/routes/schedule-routes.ts
> + *         description: Dados do horário a ser criado.
Essa sintaxe utilizada para a documentação é referente à versão 2.0, por isso não funciona ao testar a aplicação pela interface do swagger. Porém funciona perfeitamente ao utilizar outra interface de teste de API

2024-08-06 14:54 UTC, davibital commented on src/controllers/schedule-controller.ts
> +    const { dateTime, evaluatorId, status, candidateId } = req.body;
Nesse endpoint da api não é necessário receber o id do candidato ou o status, já que quando o horário de entrevista é criado, ainda não existe nenhum candidato vinculado ao horário e também o status inicial de qualquer horário de entrevista é `Não agendada`

2024-08-06 14:54 UTC, davibital commented on src/models/Schedule.ts
> +        default: null
O status default do horário é `Não agendada`

2024-08-06 14:54 UTC, davibital commented on src/services/schedule-service.ts
> +        status: status || null,
Status padrão `Não agendada`

2024-08-11 01:18 UTC, alvarolspeixoto commented on src/controllers/schedule-controller.ts
> +export const createSchedule = async (req: Request, res: Response) => {
Não entendi muito bem como seria, tu fala tipo sobre criar uma interface definindo todos parâmetros que teria no objeto da requisição/resposta? Tem algum exemplo pra eu me basear?

2024-08-12 14:13 UTC, davibital commented on src/controllers/schedule-controller.ts
> +export const createSchedule = async (req: Request, res: Response) => {
```
// Utilizando type
type ScheduleRequest = {
   evaluatorId: string;
   dateTime: Date;
};

// Utilizando interface
interface ScheduleRequest {
    evaluatorId: string;
    dateTime: Date;
};
 ```
 
Pode ser feito dessas duas formas, dá mais redigibilidade do código, além de garantir que só sejam feitas requisições com os parâmetros necessários

2024-08-19 15:32 UTC, davibital approved these changes

2024-08-19 16:08 UTC, merged